# Generated by Django 6.0.6 on 2026-06-28 18:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True, verbose_name='شناسه خارجی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('course', 'دوره آموزشی'), ('event', 'رویداد / کنگره'), ('project', 'پروژه'), ('research', 'تحقیق / مقاله')], max_length=20, verbose_name='دسته')),
                ('duration_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='مدت زمان (روز)')),
                ('impact_score', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='امتیاز تاثیر')),
                ('difficulty_rating', models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'دشوار')], default='medium', max_length=10, verbose_name='سطح دشواری')),
                ('impact_level', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], default='medium', max_length=10, verbose_name='سطح تاثیر')),
                ('resume_output', models.CharField(blank=True, max_length=255, null=True, verbose_name='خروجی رزومه')),
                ('profile_template', models.JSONField(blank=True, default=dict, help_text='{"model": "articles", "fields": {...}}', verbose_name='الگو برای پروفایل')),
                ('organizer', models.CharField(blank=True, max_length=255, null=True, verbose_name='برگزارکننده')),
                ('level', models.CharField(blank=True, max_length=50, null=True, verbose_name='سطح (دانشگاهی/ملی/بین\u200cالمللی)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فعالیت',
                'verbose_name_plural': 'فعالیت\u200cها',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=50, unique=True, verbose_name='هدف')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الگو')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('template_data', models.JSONField(verbose_name='داده\u200cهای الگو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'الگوی رودمپ',
                'verbose_name_plural': 'الگوهای رودمپ',
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان رودمپ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('goal', models.CharField(choices=[('estedad_darakhshan', 'استعداد درخشان'), ('40_emtiaz', '۴۰ امتیازی'), ('heyat_elmi', 'هیات علمی'), ('research_position', 'ریسرچ پوزیشن / فلوشیپ خارج'), ('general', 'بهبود عمومی')], max_length=50, verbose_name='هدف')),
                ('goal_details', models.TextField(blank=True, null=True, verbose_name='جزئیات هدف')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('completed', 'تکمیل\u200cشده'), ('paused', 'متوقف')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('duration_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1095)], verbose_name='مدت زمان (روز)')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='تاریخ شروع')),
                ('target_end_date', models.DateField(verbose_name='تاریخ هدف')),
                ('ai_generated', models.BooleanField(default=False, verbose_name='تولید شده توسط AI')),
                ('ai_prompt', models.TextField(blank=True, null=True, verbose_name='prompt AI')),
                ('ai_analysis', models.JSONField(blank=True, default=dict, verbose_name='تحلیل AI')),
                ('total_score', models.FloatField(default=0, verbose_name='امتیاز کل')),
                ('score_breakdown', models.JSONField(blank=True, default=dict, verbose_name='تفکیک امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نقشه راه',
                'verbose_name_plural': 'نقشه\u200cهای راه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مرحله')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('objectives', models.TextField(blank=True, null=True, verbose_name='اهداف')),
                ('status', models.CharField(choices=[('upcoming', 'در انتظار'), ('active', 'در حال انجام'), ('completed', 'تکمیل\u200cشده')], default='upcoming', max_length=20, verbose_name='وضعیت')),
                ('phase_type', models.CharField(blank=True, choices=[('foundation', 'بنیادی'), ('development', 'توسعه'), ('optimization', 'بهینه\u200cسازی'), ('execution', 'اجرا')], max_length=20, null=True, verbose_name='نوع فاز')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], default='medium', max_length=10, verbose_name='اولویت')),
                ('duration_days', models.PositiveIntegerField(verbose_name='مدت زمان (روز)')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('milestone', models.CharField(blank=True, max_length=500, null=True, verbose_name='نقطه عطف (معیار تکمیل)')),
                ('success_criteria', models.JSONField(blank=True, default=list, verbose_name='معیارهای موفقیت')),
                ('risks', models.JSONField(blank=True, default=list, verbose_name='ریسک\u200cهای احتمالی')),
                ('recommended_resources', models.JSONField(blank=True, default=list, verbose_name='منابع پیشنهادی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='roadmap.roadmap')),
            ],
            options={
                'verbose_name': 'مرحله',
                'verbose_name_plural': 'مراحل',
                'ordering': ['roadmap', 'order'],
                'unique_together': {('roadmap', 'order')},
            },
        ),
        migrations.CreateModel(
            name='StageActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تکمیل\u200cشده')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('saved_to_profile', models.CharField(blank=True, choices=[('articles', 'مقالات'), ('presentations', 'ارائه\u200cها'), ('executive_records', 'سوابق اجرایی'), ('training_courses', 'دوره\u200cهای آموزشی')], max_length=50, null=True, verbose_name='ثبت شده در')),
                ('profile_data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای پروفایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_activities', to='roadmap.activity')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_activities', to='roadmap.stage')),
            ],
            options={
                'verbose_name': 'فعالیت مرحله',
                'verbose_name_plural': 'فعالیت\u200cهای مرحله',
                'ordering': ['stage', 'order'],
                'unique_together': {('stage', 'activity', 'order')},
            },
        ),
    ]
