# Generated by Django 4.2.16 on 2026-06-10 23:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="عنوان فعالیت"),
                ),
                ("description", models.TextField(verbose_name="توضیح فعالیت")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("پژوهشی", "پژوهشی"),
                            ("بالینی", "بالینی"),
                            ("آموزشی", "آموزشی"),
                            ("نرم\u200cافزاری", "نرم\u200cافزاری"),
                            ("زبان", "زبان"),
                            ("شبکه\u200cسازی", "شبکه\u200cسازی"),
                            ("توسعه\u200cشخصی", "توسعه\u200cشخصی"),
                            ("سایر", "سایر"),
                        ],
                        max_length=30,
                        verbose_name="دسته",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("پزشکی", "پزشکی"),
                            ("دندان\u200cپزشکی", "دندان\u200cپزشکی"),
                            ("داروسازی", "داروسازی"),
                            ("پرستاری", "پرستاری"),
                            ("فیزیوتراپی", "فیزیوتراپی"),
                            ("سایر", "سایر"),
                            ("عمومی", "عمومی"),
                        ],
                        max_length=30,
                        verbose_name="حوزه تخصصی",
                    ),
                ),
                (
                    "resume_target",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("article", "مقاله"),
                            ("presentation", "ارائه"),
                            ("training_course", "دوره آموزشی"),
                            ("executive_record", "سابقه اجرایی"),
                            ("skill", "مهارت"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveSmallIntegerField(
                        default=7,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                        verbose_name="مدت زمان (روز)",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[("آسان", "آسان"), ("متوسط", "متوسط"), ("سخت", "سخت")],
                        default="متوسط",
                        max_length=10,
                        verbose_name="سطح سختی",
                    ),
                ),
                ("resume_output", models.TextField(verbose_name="خروجی رزومه\u200cای")),
                (
                    "prerequisites",
                    models.TextField(blank=True, verbose_name="پیش\u200cنیازها"),
                ),
                (
                    "resources",
                    models.TextField(blank=True, verbose_name="منابع و مراجع"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "فعالیت",
                "verbose_name_plural": "فعالیت\u200cها",
                "ordering": ["category", "title"],
            },
        ),
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="عنوان رود مپ"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیح رود مپ"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("پیش\u200cنویس", "پیش\u200cنویس"),
                            ("فعال", "فعال"),
                            ("تکمیل\u200cشده", "تکمیل\u200cشده"),
                            ("متوقف\u200cشده", "متوقف\u200cشده"),
                        ],
                        default="پیش\u200cنویس",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "رود مپ",
                "verbose_name_plural": "رود مپ\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان مرحله")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیح مرحله"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("پیش\u200cرو", "پیش\u200cرو"),
                            ("در حال انجام", "در حال انجام"),
                            ("تکمیل\u200cشده", "تکمیل\u200cشده"),
                        ],
                        default="پیش\u200cرو",
                        max_length=20,
                        verbose_name="وضعیت مرحله",
                    ),
                ),
                ("objectives", models.TextField(verbose_name="اهداف مرحله")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="roadmap.roadmap",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرحله",
                "verbose_name_plural": "مراحل",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StageChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="عنوان چک\u200cلیست"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="تکمیل\u200cشده"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklists",
                        to="roadmap.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "چک\u200cلیست",
                "verbose_name_plural": "چک\u200cلیست\u200cها",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StageActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="تکمیل\u200cشده"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت\u200cها")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roadmap.activity",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_activities",
                        to="roadmap.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "فعالیت مرحله",
                "verbose_name_plural": "فعالیت\u200cهای مرحله",
                "ordering": ["order"],
                "unique_together": {("stage", "activity")},
            },
        ),
        migrations.CreateModel(
            name="RoadmapActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roadmap.activity",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap_activities",
                        to="accounts.profile",
                    ),
                ),
                (
                    "stage_activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_record",
                        to="roadmap.stageactivity",
                    ),
                ),
            ],
            options={
                "verbose_name": "فعالیت تکمیل شده رودمپ",
                "verbose_name_plural": "فعالیت\u200cهای تکمیل شده رودمپ",
            },
        ),
    ]
