# Generated by Django 6.0.6 on 2026-06-29 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageactivity',
            name='activity_source',
            field=models.CharField(choices=[('static', 'از لیست ثابت'), ('custom', 'دستی ایجاد شده')], default='custom', max_length=20, verbose_name='منبع فعالیت'),
        ),
        migrations.AddField(
            model_name='stageactivity',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان واقعی'),
        ),
        migrations.AddField(
            model_name='stageactivity',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع واقعی'),
        ),
        migrations.AddField(
            model_name='stageactivity',
            name='checkpoints',
            field=models.JSONField(blank=True, default=list, help_text='[{"title": "...", "is_completed": false, "date": "..."}]', verbose_name='نقاط کنترل'),
        ),
        migrations.AddField(
            model_name='stageactivity',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها'),
        ),
        migrations.AddField(
            model_name='stageactivity',
            name='outcome_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای نتیجه'),
        ),
        migrations.AddField(
            model_name='stageactivity',
            name='progress_percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد پیشرفت'),
        ),
        migrations.AddField(
            model_name='stageactivity',
            name='resources',
            field=models.JSONField(blank=True, default=list, help_text='[{"title": "...", "url": "...", "type": "link"}]', verbose_name='منابع'),
        ),
        migrations.AddField(
            model_name='stageactivity',
            name='result_summary',
            field=models.TextField(blank=True, null=True, verbose_name='خلاصه نتایج'),
        ),
        migrations.AddField(
            model_name='stageactivity',
            name='static_item_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای آیتم ثابت'),
        ),
        migrations.AddField(
            model_name='stageactivity',
            name='static_item_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه آیتم ثابت'),
        ),
    ]
