# Generated by Django 4.2.16 on 2026-06-11 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="resume_target",
        ),
    ]
