# Generated by Django 4.2.16 on 2026-07-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_stageactivity_activity_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageactivity',
            name='checkpoints',
            field=models.JSONField(blank=True, default=list, help_text='[{"id": 1, "source_type": "manual|course|project", "title": "...", "description": "...", "priority": "low|medium|high", "due_date": null, "notes": "...", "source_id": null, "source_url": null, "is_completed": false, "date": null}]', verbose_name='نقاط کنترل'),
        ),
    ]
