# Generated by Django 4.2.16 on 2026-06-11 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0002_remove_activity_resume_target"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RoadmapActivity",
        ),
    ]
