# Generated by Django 4.2.16 on 2026-06-11 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("roadmap", "0003_delete_roadmapactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="resume_target",
            field=models.CharField(
                blank=True,
                choices=[
                    ("article", "مقاله"),
                    ("presentation", "ارائه"),
                    ("training_course", "دوره آموزشی"),
                    ("executive_record", "سابقه اجرایی"),
                    ("skill", "مهارت"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="RoadmapActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roadmap.activity",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap_activities",
                        to="accounts.profile",
                    ),
                ),
                (
                    "stage_activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_record",
                        to="roadmap.stageactivity",
                    ),
                ),
            ],
            options={
                "verbose_name": "فعالیت تکمیل شده رودمپ",
                "verbose_name_plural": "فعالیت\u200cهای تکمیل شده رودمپ",
            },
        ),
    ]
