# Generated by Django 4.2.16 on 2026-06-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0004_activity_resume_target_roadmapactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="profile_template",
            field=models.JSONField(
                blank=True,
                help_text="JSON template for saving activity into profile",
                null=True,
            ),
        ),
    ]
