# Generated by Django 4.2.16 on 2026-06-11 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0005_activity_profile_template"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StageChecklist",
        ),
    ]
