# Generated by Django 6.0.6 on 2026-06-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0006_delete_stagechecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='suitable_goals',
            field=models.JSONField(blank=True, default=list, help_text='لیست اهدافی که این فعالیت برای آن\u200cها مناسب است. خالی = مناسب همه اهداف', verbose_name='اهداف مناسب'),
        ),
    ]
