# Generated by Django 6.0.6 on 2026-06-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0007_activity_suitable_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='estimated_weeks',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تخمین هفته'),
        ),
        migrations.AddField(
            model_name='stage',
            name='milestone',
            field=models.TextField(blank=True, help_text='خروجی ملموسی که نشان\u200cدهنده تکمیل این مرحله است', verbose_name='نقطه عطف (معیار تکمیل)'),
        ),
        migrations.AddField(
            model_name='stage',
            name='phase_type',
            field=models.CharField(blank=True, choices=[('foundation', 'پایه\u200cریزی'), ('development', 'توسعه'), ('advancement', 'پیشرفت'), ('excellence', 'تعالی')], default='development', max_length=20, verbose_name='نوع فاز'),
        ),
        migrations.AddField(
            model_name='stage',
            name='priority',
            field=models.CharField(blank=True, choices=[('critical', 'بحرانی'), ('high', 'بالا'), ('medium', 'متوسط'), ('low', 'پایین')], default='medium', max_length=10, verbose_name='اولویت'),
        ),
        migrations.AddField(
            model_name='stage',
            name='recommended_resources',
            field=models.JSONField(blank=True, default=list, help_text='منابع پیشنهادی AI برای این مرحله', verbose_name='منابع پیشنهادی'),
        ),
        migrations.AddField(
            model_name='stage',
            name='risks',
            field=models.JSONField(blank=True, default=list, help_text='ریسک\u200cهای احتمالی این مرحله', verbose_name='ریسک\u200cها'),
        ),
        migrations.AddField(
            model_name='stage',
            name='success_criteria',
            field=models.JSONField(blank=True, default=list, help_text='لیست معیارهای قابل سنجش برای تکمیل مرحله', verbose_name='معیارهای موفقیت'),
        ),
    ]
