# Generated by Django 6.0.6 on 2026-06-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0008_stage_estimated_weeks_stage_milestone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='estimated_weeks',
        ),
    ]
