# Generated by Django 4.2.16 on 2026-07-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='توضیح کوتاه')),
                ('url_name', models.CharField(blank=True, help_text='مثال: regulation_assessment:evaluation_form', max_length=150, verbose_name='نام URL (namespace:name)')),
                ('external_url', models.CharField(blank=True, max_length=300, verbose_name='لینک جایگزین / ثابت')),
                ('icon_svg', models.TextField(blank=True, help_text='محتوای داخل تگ <svg>...</svg> را بدون تگ بیرونی paste کنید.', verbose_name='کد SVG آیکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_new', models.BooleanField(default=True, verbose_name='برچسب «جدید»')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ابزار',
                'verbose_name_plural': 'ابزارها',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
