# Generated by Django 4.2.16 on 2026-07-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['category__order', '-created_at'], 'verbose_name': 'دوره', 'verbose_name_plural': 'دوره\u200cها'},
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.SlugField(help_text='شناسه یکتا مثل ola_001', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='long_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_desc',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
