# Generated by Django 6.0.6 on 2026-06-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان رویداد')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('section', models.CharField(blank=True, max_length=100, verbose_name='بخش')),
                ('short_description', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('compiler', models.CharField(blank=True, max_length=200, verbose_name='تهیه\u200cکننده')),
                ('audience', models.TextField(blank=True, verbose_name='مخاطبان')),
                ('goal', models.TextField(blank=True, verbose_name='هدف')),
                ('resume_impact', models.CharField(blank=True, max_length=50, verbose_name='اثر در رزومه')),
                ('activity_type', models.CharField(blank=True, max_length=200, verbose_name='نوع فعالیت')),
                ('activity_level', models.CharField(blank=True, max_length=200, verbose_name='سطح فعالیت')),
                ('difficulty', models.CharField(blank=True, max_length=50, verbose_name='سطح دشواری')),
                ('main_advantage', models.TextField(blank=True, verbose_name='مزیت اصلی')),
                ('suitable_for', models.TextField(blank=True, verbose_name='مناسب برای')),
                ('required_time', models.CharField(blank=True, max_length=200, verbose_name='زمان موردنیاز')),
                ('intro', models.TextField(blank=True, verbose_name='معرفی کامل')),
                ('research_audiences', models.TextField(blank=True, verbose_name='مخاطبان پژوهشی')),
                ('skills_learned', models.TextField(blank=True, verbose_name='مهارت\u200cهای آموخته\u200cشده')),
                ('completion_steps', models.JSONField(blank=True, default=list, verbose_name='مراحل تکمیل')),
                ('terms_and_conditions', models.JSONField(blank=True, default=list, verbose_name='شرایط و ضوابط')),
                ('benefits', models.JSONField(blank=True, default=dict, verbose_name='مزایا')),
                ('common_mistakes', models.JSONField(blank=True, default=list, verbose_name='اشتباهات رایج')),
                ('practical_recommendations', models.JSONField(blank=True, default=list, verbose_name='توصیه\u200cهای کاربردی')),
                ('similar_opportunities', models.JSONField(blank=True, default=list, verbose_name='فرصت\u200cهای مشابه')),
                ('inline_cta_buttons', models.JSONField(blank=True, default=list, verbose_name='دکمه\u200cهای میان\u200cخطی')),
                ('page_cta_buttons', models.JSONField(blank=True, default=list, verbose_name='دکمه\u200cهای صفحه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویدادها',
                'ordering': ['title'],
            },
        ),
    ]
