# Generated by Django 6.0.6 on 2026-06-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='audience',
            field=models.JSONField(blank=True, default=list, verbose_name='مخاطبان'),
        ),
        migrations.AlterField(
            model_name='event',
            name='research_audiences',
            field=models.JSONField(blank=True, default=list, verbose_name='مخاطبان پژوهشی'),
        ),
        migrations.AlterField(
            model_name='event',
            name='skills_learned',
            field=models.JSONField(blank=True, default=list, verbose_name='مهارت\u200cهای آموخته\u200cشده'),
        ),
    ]
