# Generated by Django 4.2.16 on 2026-07-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_hub', '0002_alter_event_audience_alter_event_research_audiences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('سایر', 'سایر'), ('جشنواره ها', 'جشنواره ها'), ('المپیادهای علمی', 'المپیادهای علمی'), ('برنامه های نخبگانی', 'برنامه های نخبگانی'), ('رویدادهای پژوهشی', 'رویدادهای پژوهشی'), ('رویدادهای فناورانه', 'رویدادهای فناورانه'), ('فرصت های بین المللی', 'فرصت های بین المللی')], default='سایر', max_length=20, verbose_name='دسته بندی'),
        ),
    ]
