# Generated by Django 4.2.16 on 2026-06-09 08:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="نام خانوادگی"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("مرد", "مرد"), ("زن", "زن")],
                        max_length=10,
                        verbose_name="جنسیت",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[("مجرد", "مجرد"), ("متأهل", "متأهل")],
                        max_length=10,
                        verbose_name="وضعیت تأهل",
                    ),
                ),
                (
                    "military_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "مربوط نیست"),
                            ("معاف", "معاف"),
                            ("طرح پزشکی", "طرح پزشکی"),
                            ("سرباز", "سرباز"),
                            ("پایان خدمت", "پایان خدمت"),
                        ],
                        max_length=20,
                        verbose_name="وضعیت سربازی",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="عنوان شغلی"
                    ),
                ),
                (
                    "birth_date",
                    models.CharField(max_length=20, verbose_name="تاریخ تولد"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="ایران", max_length=100, verbose_name="کشور"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="استان / شهر محل سکونت"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="شماره موبایل")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                (
                    "website",
                    models.URLField(blank=True, verbose_name="وب\u200cسایت شخصی"),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="کد ملی / شماره پاسپورت"
                    ),
                ),
                (
                    "orcid",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="شناسه ORCID"
                    ),
                ),
                (
                    "proposal_count",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="تعداد پروپوزال\u200cها"
                    ),
                ),
                (
                    "proposal_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "انتخاب کنید"),
                            ("همه در جریان", "همه در جریان"),
                            ("همه خاتمه\u200cیافته", "همه خاتمه\u200cیافته"),
                            ("ترکیبی", "ترکیبی (برخی در جریان، برخی خاتمه\u200cیافته)"),
                        ],
                        max_length=50,
                        verbose_name="وضعیت پروپوزال\u200cها",
                    ),
                ),
                (
                    "software_skills",
                    models.TextField(
                        blank=True, verbose_name="مهارت\u200cهای نرم\u200cافزاری"
                    ),
                ),
                (
                    "writing_skills",
                    models.TextField(blank=True, verbose_name="مهارت\u200cهای نگارشی"),
                ),
                (
                    "clinical_certs",
                    models.TextField(
                        blank=True, verbose_name="گواهینامه\u200cهای مهارتی"
                    ),
                ),
                (
                    "clinical_exp",
                    models.TextField(
                        blank=True, verbose_name="سوابق کار دانشجویی و بالینی"
                    ),
                ),
                (
                    "procedures",
                    models.TextField(
                        blank=True, verbose_name="مهارت\u200cهای پروسیجرال"
                    ),
                ),
                (
                    "native_lang",
                    models.CharField(
                        default="فارسی", max_length=50, verbose_name="زبان مادری"
                    ),
                ),
                (
                    "english_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "انتخاب کنید"),
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ],
                        max_length=5,
                        verbose_name="سطح زبان انگلیسی",
                    ),
                ),
                (
                    "lang_cert",
                    models.TextField(blank=True, verbose_name="مدرک زبان انگلیسی"),
                ),
                (
                    "other_langs",
                    models.TextField(blank=True, verbose_name="سایر زبان\u200cها"),
                ),
                (
                    "extracurricular",
                    models.TextField(
                        blank=True, verbose_name="فعالیت\u200cهای فوق برنامه"
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("استعداد درخشان", "استعداد درخشان"),
                            ("۴۰ امتیازی", "۴۰ امتیازی"),
                            ("هیات علمی", "هیات علمی"),
                            (
                                "ریسرچ پوزیشن / فلوشیپ خارج",
                                "ریسرچ پوزیشن / فلوشیپ خارج",
                            ),
                        ],
                        max_length=50,
                        verbose_name="هدف نهایی حرفه\u200cای",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="حوزه تخصصی"
                    ),
                ),
                (
                    "goal_notes",
                    models.TextField(blank=True, verbose_name="توضیحات اهداف"),
                ),
                (
                    "service_plan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "انتخاب کنید"),
                            ("مشمول نیستم", "مشمول نیستم"),
                            ("در حال گذراندن", "در حال گذراندن"),
                            ("پایان یافته", "پایان یافته"),
                        ],
                        max_length=30,
                        verbose_name="وضعیت طرح نیروی انسانی",
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(blank=True, verbose_name="متن خام پروفایل"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پروفایل",
                "verbose_name_plural": "پروفایل\u200cها",
            },
        ),
        migrations.CreateModel(
            name="TrainingCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان دوره"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("پژوهشی", "پژوهشی"),
                            ("بالینی", "بالینی"),
                            ("آموزشی", "آموزشی"),
                            ("نرم\u200cافزاری", "نرم\u200cافزاری"),
                            ("زبان", "زبان"),
                            ("سایر", "سایر"),
                        ],
                        max_length=30,
                        verbose_name="دسته",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("تکمیل\u200cشده", "تکمیل\u200cشده"),
                            ("در حال گذراندن", "در حال گذراندن"),
                            ("ناتمام", "ناتمام"),
                        ],
                        max_length=30,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "organizer",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="برگزارکننده"
                    ),
                ),
                (
                    "date",
                    models.CharField(blank=True, max_length=20, verbose_name="تاریخ"),
                ),
                (
                    "certificate",
                    models.CharField(
                        blank=True,
                        choices=[("دارد", "دارد"), ("ندارد", "ندارد")],
                        max_length=10,
                        verbose_name="گواهی",
                    ),
                ),
                (
                    "skills_gained",
                    models.TextField(blank=True, verbose_name="مهارت کسب\u200cشده"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_courses",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "دوره آموزشی",
                "verbose_name_plural": "دوره\u200cهای آموزشی",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="SocialProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "social_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LinkedIn", "LinkedIn"),
                            ("GitHub", "GitHub"),
                            ("Google Scholar", "Google Scholar"),
                            ("ResearchGate", "ResearchGate"),
                            ("Dribbble", "Dribbble"),
                            ("Twitter / X", "Twitter / X"),
                            ("Instagram", "Instagram"),
                            ("سایر", "سایر"),
                        ],
                        max_length=30,
                        verbose_name="نوع شبکه",
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="لینک پروفایل")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_profiles",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "پروفایل اجتماعی",
                "verbose_name_plural": "پروفایل\u200cهای اجتماعی",
            },
        ),
        migrations.CreateModel(
            name="Presentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="عنوان ارائه"
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نام کنگره / رویداد"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("بین\u200cالمللی", "بین\u200cالمللی"),
                            ("ملی", "ملی"),
                            ("قطبی", "قطبی"),
                            ("دانشگاهی", "دانشگاهی"),
                        ],
                        max_length=20,
                        verbose_name="سطح رویداد",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("برگزیده / جایزه", "برگزیده / جایزه"),
                            ("ارائه عادی", "ارائه عادی"),
                        ],
                        max_length=30,
                        verbose_name="نتیجه",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presentations",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "ارائه",
                "verbose_name_plural": "ارائه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="ExecutiveRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان سمت / نام تشکل"
                    ),
                ),
                (
                    "start_date",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="تاریخ شروع"
                    ),
                ),
                (
                    "end_date",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="تاریخ پایان"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executive_records",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "سابقه اجرایی",
                "verbose_name_plural": "سوابق اجرایی",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("پزشکی", "پزشکی"),
                            ("دندان\u200cپزشکی", "دندان\u200cپزشکی"),
                            ("داروسازی", "داروسازی"),
                            ("پرستاری", "پرستاری"),
                            ("فیزیوتراپی", "فیزیوتراپی"),
                            ("سایر", "سایر"),
                        ],
                        max_length=30,
                        verbose_name="رشته تحصیلی",
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("کارشناسی", "کارشناسی"),
                            ("کارشناسی ارشد", "کارشناسی ارشد"),
                            ("دکتری عمومی", "دکتری عمومی"),
                            ("دکتری تخصصی", "دکتری تخصصی"),
                        ],
                        max_length=20,
                        verbose_name="مقطع تحصیلی",
                    ),
                ),
                (
                    "university",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="دانشگاه"
                    ),
                ),
                (
                    "uni_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("تیپ ۱", "تیپ ۱"),
                            ("تیپ ۲", "تیپ ۲"),
                            ("تیپ ۳", "تیپ ۳"),
                        ],
                        max_length=10,
                        verbose_name="تیپ دانشگاه",
                    ),
                ),
                (
                    "start_date",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="تاریخ شروع"
                    ),
                ),
                (
                    "end_date",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="تاریخ پایان"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("علوم پایه", "علوم پایه"),
                            ("فیزیوپات", "فیزیوپات"),
                            ("استاژری", "استاژری"),
                            ("اینترنی", "اینترنی"),
                            ("فارغ\u200cالتحصیل", "فارغ\u200cالتحصیل"),
                        ],
                        max_length=20,
                        verbose_name="مرحله تحصیلی",
                    ),
                ),
                (
                    "current_term",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="ترم فعلی",
                    ),
                ),
                (
                    "remaining_terms",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(20)],
                        verbose_name="ترم\u200cهای باقیمانده",
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="معدل",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "تحصیلات",
                "verbose_name_plural": "تحصیلات",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="عنوان مقاله"
                    ),
                ),
                (
                    "journal",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نام ژورنال"
                    ),
                ),
                (
                    "impact_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Impact Factor",
                    ),
                ),
                (
                    "quartile",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Q1", "Q1"),
                            ("Q2", "Q2"),
                            ("Q3", "Q3"),
                            ("Q4", "Q4"),
                        ],
                        max_length=2,
                        verbose_name="چارک",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1370),
                            django.core.validators.MaxValueValidator(1410),
                        ],
                        verbose_name="سال چاپ",
                    ),
                ),
                (
                    "author_rank",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="نفر چندم"
                    ),
                ),
                (
                    "total_authors",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="تعداد نویسندگان"
                    ),
                ),
                (
                    "index",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ISI / Web of Science", "ISI / Web of Science"),
                            ("Scopus", "Scopus"),
                            ("PubMed", "PubMed"),
                            ("ISI + Scopus", "ISI + Scopus"),
                            ("سایر", "سایر"),
                        ],
                        max_length=30,
                        verbose_name="ایندکس",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات",
                "ordering": ["-year"],
            },
        ),
    ]
