# Generated by Django 4.2.16 on 2026-07-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='english_level',
            field=models.CharField(blank=True, choices=[('', 'انتخاب کنید'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='', max_length=5, verbose_name='سطح زبان انگلیسی'),
        ),
    ]
