# Generated by Django 4.2.16 on 2026-07-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_english_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='english_level',
            field=models.CharField(blank=True, choices=[('', 'انتخاب کنید'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=5, verbose_name='سطح زبان انگلیسی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='native_lang',
            field=models.CharField(blank=True, max_length=50, verbose_name='زبان مادری'),
        ),
    ]
