# Generated by Django 6.0.6 on 2026-06-29 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('course', 'دوره آموزشی'), ('event', 'رویداد / کنگره'), ('project', 'پروژه'), ('research', 'تحقیق / مقاله')], max_length=20)),
                ('duration_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('impact_score', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('difficulty_rating', models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'دشوار')], default='medium', max_length=10)),
                ('impact_level', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], default='medium', max_length=10)),
                ('organizer', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فعالیت',
                'verbose_name_plural': 'فعالیت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
