# Generated by Django 6.0.6 on 2026-06-29 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('roadmap', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان نقطه کنترل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تکمیل\u200cشده')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نقطه کنترل فعالیت',
                'verbose_name_plural': 'نقاط کنترل فعالیت',
                'ordering': ['activity_log', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل\u200cشده'), ('paused', 'متوقف'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='تاریخ شروع')),
                ('target_completion_date', models.DateField(verbose_name='تاریخ هدف تکمیل')),
                ('actual_completion_date', models.DateField(blank=True, null=True, verbose_name='تاریخ واقعی تکمیل')),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='درصد پیشرفت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('result_summary', models.TextField(blank=True, null=True, verbose_name='خلاصه نتایج')),
                ('outcome_data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای نتیجه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='roadmap.activity')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='roadmap.roadmap')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='roadmap.stage')),
                ('stage_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='roadmap.stageactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ثبت فعالیت',
                'verbose_name_plural': 'ثبت\u200cهای فعالیت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان منبع')),
                ('resource_type', models.CharField(choices=[('link', 'لینک'), ('file', 'فایل'), ('book', 'کتاب'), ('course', 'دوره'), ('other', 'سایر')], max_length=50, verbose_name='نوع منبع')),
                ('url', models.URLField(blank=True, null=True, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='activity.activitylog', verbose_name='ثبت فعالیت')),
            ],
            options={
                'verbose_name': 'منبع فعالیت',
                'verbose_name_plural': 'منابع فعالیت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AtActivity',
        ),
        migrations.AddField(
            model_name='activitycheckpoint',
            name='activity_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='activity.activitylog', verbose_name='ثبت فعالیت'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created_at'], name='activity_ac_user_id_9aae35_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['roadmap', 'status'], name='activity_ac_roadmap_cc6611_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activitycheckpoint',
            unique_together={('activity_log', 'order')},
        ),
    ]
