# Generated by Django 6.0.6 on 2026-06-30 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideoInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید به فرمت 09xxxxxxxxx باشد', regex='^09\\d{9}$')], verbose_name='شماره تلفن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('total_score', models.IntegerField(default=0, verbose_name='امتیاز کل')),
                ('breakdown', models.JSONField(default=dict, verbose_name='جزئیات امتیازات')),
                ('requested_courses', models.JSONField(default=list, verbose_name='دوره\u200cهای درخواستی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'علاقه\u200cمندی کاربر به ویدیو',
                'verbose_name_plural': 'علاقه\u200cمندی\u200cهای کاربران به ویدیوها',
                'ordering': ['-updated_at'],
            },
        ),
    ]
