# roadmap/static_items.py
"""
لیست ثابت فعالیت‌های قابل انتخاب برای دانشجویان پزشکی.
هر آیتم شامل اطلاعات کامل برای نمایش در UI و ذخیره در دیتابیس است.
"""

STATIC_ITEMS = {
    "course": [
        {
            "id": "c1",
            "title": "کارگاه مقاله‌نویسی علمی ISI",
            "description": "آموزش اصول نگارش مقالات علمی برای ژورنال‌های بین‌المللی ISI/Scopus شامل ساختار IMRAD، نگارش Abstract و Cover Letter",
            "organizer": "معاونت تحقیقات دانشگاه",
            "level": "university",
            "estimated_duration_days": 14,
            "impact_score": 8,
            "difficulty": "medium",
            "resume_section": "training_courses",
            "tags": ["مقاله‌نویسی", "ISI", "پژوهش"],
            "prerequisites": [],
            "outcomes": ["توانایی نگارش مقاله ISI", "آشنایی با peer review", "مهارت ارسال به ژورنال"],
        },
        {
            "id": "c2",
            "title": "کارگاه پروپوزال‌نویسی",
            "description": "یادگیری طراحی و نگارش پروپوزال تحقیقاتی برای ارائه به معاونت تحقیقات، شامل تعریف مسئله، مرور متون و روش‌شناسی",
            "organizer": "معاونت تحقیقات دانشگاه",
            "level": "university",
            "estimated_duration_days": 10,
            "impact_score": 7,
            "difficulty": "medium",
            "resume_section": "training_courses",
            "tags": ["پروپوزال", "طرح تحقیقاتی", "روش‌شناسی"],
            "prerequisites": [],
            "outcomes": ["نوشتن پروپوزال استاندارد", "تعریف سوال تحقیق", "محاسبه حجم نمونه"],
        },
        {
            "id": "c3",
            "title": "دوره آمار پزشکی و SPSS",
            "description": "آموزش جامع آمار توصیفی و استنباطی برای پزشکان، تحلیل داده با نرم‌افزار SPSS، تفسیر p-value و آزمون‌های آماری رایج",
            "organizer": "آنلاین / دانشگاه",
            "level": "university",
            "estimated_duration_days": 30,
            "impact_score": 9,
            "difficulty": "hard",
            "resume_section": "training_courses",
            "tags": ["آمار", "SPSS", "تحلیل داده"],
            "prerequisites": [],
            "outcomes": ["تسلط بر SPSS", "انجام آنالیز آماری مقاله", "تفسیر نتایج آماری"],
        },
        {
            "id": "c4",
            "title": "دوره زبان تخصصی پزشکی (Medical English)",
            "description": "تقویت مهارت‌های خواندن، نوشتن و مکالمه به زبان انگلیسی در حوزه پزشکی، آشنایی با ترمینولوژی تخصصی و نگارش علمی به انگلیسی",
            "organizer": "آنلاین (Coursera / آموزشگاه)",
            "level": "university",
            "estimated_duration_days": 45,
            "impact_score": 8,
            "difficulty": "medium",
            "resume_section": "training_courses",
            "tags": ["زبان انگلیسی", "Medical English", "مهارت زبانی"],
            "prerequisites": [],
            "outcomes": ["بهبود نگارش انگلیسی", "توانایی ارائه در کنفرانس بین‌المللی", "مطالعه متون پزشکی"],
        },
        {
            "id": "c5",
            "title": "کارگاه مهارت‌های ارائه علمی (Presentation Skills)",
            "description": "آموزش اصول ارائه حرفه‌ای در کنفرانس‌های علمی، طراحی اسلاید مؤثر، زبان بدن، مدیریت سوال و جواب و Poster presentation",
            "organizer": "دانشگاه / معاونت پژوهش",
            "level": "university",
            "estimated_duration_days": 7,
            "impact_score": 7,
            "difficulty": "easy",
            "resume_section": "training_courses",
            "tags": ["ارائه علمی", "Presentation", "مهارت نرم"],
            "prerequisites": [],
            "outcomes": ["ارائه حرفه‌ای در کنفرانس", "طراحی Poster", "مدیریت استرس ارائه"],
        },
        {
            "id": "c6",
            "title": "دوره مدیریت منابع (EndNote / Zotero / Mendeley)",
            "description": "آموزش استفاده حرفه‌ای از نرم‌افزارهای مدیریت منابع برای ساماندهی مقالات، درج Reference خودکار و کار با انواع استایل‌های ارجاع‌دهی",
            "organizer": "آنلاین",
            "level": "university",
            "estimated_duration_days": 5,
            "impact_score": 6,
            "difficulty": "easy",
            "resume_section": "training_courses",
            "tags": ["EndNote", "Zotero", "مدیریت منابع"],
            "prerequisites": [],
            "outcomes": ["مدیریت منابع مقاله", "ساخت کتابخانه تحقیقاتی", "درج Reference خودکار"],
        },
        {
            "id": "c7",
            "title": "دوره Systematic Review و Meta-Analysis",
            "description": "آموزش گام‌به‌گام انجام مرور سیستماتیک و متاآنالیز: تعریف PICO، جستجوی پایگاه‌های داده، ارزیابی کیفیت مطالعات و تحلیل با RevMan",
            "organizer": "آنلاین / دانشگاه",
            "level": "university",
            "estimated_duration_days": 20,
            "impact_score": 9,
            "difficulty": "hard",
            "resume_section": "training_courses",
            "tags": ["Systematic Review", "Meta-Analysis", "PICO"],
            "prerequisites": ["c3"],
            "outcomes": ["انجام systematic review مستقل", "تسلط بر RevMan", "نگارش مقاله مرور"],
        },
        {
            "id": "c8",
            "title": "کارگاه اخلاق در پژوهش پزشکی",
            "description": "آشنایی با اصول اخلاق پژوهش، رضایت آگاهانه، کمیته اخلاق، پلاژیاریسم، تضاد منافع و دستورالعمل‌های بین‌المللی (Declaration of Helsinki)",
            "organizer": "دانشگاه / وزارت بهداشت",
            "level": "national",
            "estimated_duration_days": 8,
            "impact_score": 6,
            "difficulty": "easy",
            "resume_section": "training_courses",
            "tags": ["اخلاق پژوهش", "کمیته اخلاق", "IRCT"],
            "prerequisites": [],
            "outcomes": ["آشنایی با اخلاق پژوهش", "توانایی دریافت تأییدیه اخلاق", "جلوگیری از مشکلات قانونی"],
        },
        {
            "id": "c9",
            "title": "دوره R برای تحلیل داده‌های پزشکی",
            "description": "یادگیری زبان برنامه‌نویسی R برای آنالیز آماری پیشرفته، رسم نمودار با ggplot2، تحلیل بقا (Survival Analysis) و رگرسیون لجستیک",
            "organizer": "آنلاین (Coursera / edX)",
            "level": "university",
            "estimated_duration_days": 35,
            "impact_score": 8,
            "difficulty": "hard",
            "resume_section": "training_courses",
            "tags": ["R", "آمار پیشرفته", "ggplot2", "داده"],
            "prerequisites": ["c3"],
            "outcomes": ["تحلیل آماری پیشرفته", "رسم نمودار حرفه‌ای", "کدنویسی برای پژوهش"],
        },
        {
            "id": "c10",
            "title": "کارگاه Clinical Trial Design",
            "description": "آموزش طراحی کارآزمایی بالینی، تعریف endpoint، randomization، blinding، محاسبه حجم نمونه و ثبت در IRCT",
            "organizer": "دانشگاه / معاونت تحقیقات",
            "level": "national",
            "estimated_duration_days": 12,
            "impact_score": 9,
            "difficulty": "hard",
            "resume_section": "training_courses",
            "tags": ["Clinical Trial", "RCT", "IRCT", "طراحی مطالعه"],
            "prerequisites": ["c3", "c8"],
            "outcomes": ["طراحی RCT", "ثبت در IRCT", "نوشتن پروتکل کارآزمایی"],
        },
        {
            "id": "c11",
            "title": "دوره Bioinformatics پایه برای پزشکان",
            "description": "آشنایی با ابزارهای بیوانفورماتیک، جستجو در پایگاه‌های NCBI/PubMed/UniProt، آنالیز توالی، BLAST و مقدمه‌ای بر genomics",
            "organizer": "آنلاین",
            "level": "university",
            "estimated_duration_days": 25,
            "impact_score": 7,
            "difficulty": "medium",
            "resume_section": "training_courses",
            "tags": ["بیوانفورماتیک", "NCBI", "genomics"],
            "prerequisites": [],
            "outcomes": ["کار با NCBI", "آنالیز توالی", "آشنایی با genomics"],
        },
        {
            "id": "c12",
            "title": "کارگاه گرنت‌نویسی و جذب بودجه تحقیقاتی",
            "description": "آموزش نگارش پروپوزال برای جذب بودجه از سازمان‌های داخلی و خارجی، آشنایی با گرنت‌های دانشجویی، Wellcome Trust و NIH grants",
            "organizer": "معاونت تحقیقات / دانشگاه",
            "level": "national",
            "estimated_duration_days": 10,
            "impact_score": 8,
            "difficulty": "hard",
            "resume_section": "training_courses",
            "tags": ["گرنت", "بودجه تحقیقاتی", "فاندینگ"],
            "prerequisites": ["c2"],
            "outcomes": ["نگارش grant proposal", "آشنایی با منابع مالی تحقیقات", "جذب حمایت مالی"],
        },
    ],

    "event": [
        {
            "id": "e1",
            "title": "کنگره سراسری پزشکی",
            "description": "شرکت به عنوان شرکت‌کننده یا ارائه‌دهنده در کنگره‌های سراسری تخصصی در حوزه پزشکی، فرصت networking و آشنایی با آخرین یافته‌های علمی",
            "organizer": "انجمن علمی تخصصی / وزارت بهداشت",
            "level": "national",
            "estimated_duration_days": 3,
            "impact_score": 7,
            "difficulty": "easy",
            "resume_section": "presentations",
            "tags": ["کنگره", "ملی", "networking"],
            "outcomes": ["گواهی شرکت", "networking با متخصصان", "آشنایی با تحقیقات جدید"],
        },
        {
            "id": "e2",
            "title": "سمپوزیوم دانشجویی علوم پزشکی",
            "description": "شرکت در سمپوزیوم‌های دانشجویی، ارائه نتایج تحقیقات به صورت Oral یا Poster، رقابت با دانشجویان سایر دانشگاه‌ها",
            "organizer": "دانشگاه / انجمن دانشجویی",
            "level": "university",
            "estimated_duration_days": 1,
            "impact_score": 6,
            "difficulty": "easy",
            "resume_section": "presentations",
            "tags": ["سمپوزیوم", "دانشجویی", "Oral presentation"],
            "outcomes": ["گواهی ارائه", "تجربه ارائه علمی", "آشنایی با همتایان"],
        },
        {
            "id": "e3",
            "title": "کنفرانس بین‌المللی تحقیقات پزشکی",
            "description": "شرکت در کنفرانس‌های بین‌المللی خارج یا داخل کشور با ارائه Abstract پذیرفته‌شده، تجربه بین‌المللی و تعامل با محققان جهانی",
            "organizer": "سازمان‌های بین‌المللی / IFMSA",
            "level": "international",
            "estimated_duration_days": 5,
            "impact_score": 10,
            "difficulty": "hard",
            "resume_section": "presentations",
            "tags": ["بین‌المللی", "کنفرانس", "Abstract"],
            "outcomes": ["گواهی بین‌المللی", "تجربه بین‌المللی", "ارتباط با محققان خارجی"],
        },
        {
            "id": "e4",
            "title": "جشنواره شهید رهنمون (دانشجویان شاهد و ایثارگر)",
            "description": "شرکت در جشنواره ملی شهید رهنمون و ارائه دستاوردهای علمی و پژوهشی، مناسب برای دانشجویان واجد شرایط",
            "organizer": "بنیاد شهید / وزارت بهداشت",
            "level": "national",
            "estimated_duration_days": 2,
            "impact_score": 7,
            "difficulty": "medium",
            "resume_section": "executive_records",
            "tags": ["جشنواره", "ملی", "رهنمون"],
            "outcomes": ["تقدیرنامه ملی", "امتیاز برای استعداد درخشان", "recognition ملی"],
        },
        {
            "id": "e5",
            "title": "Journal Club دانشگاهی",
            "description": "شرکت فعال در جلسات Journal Club گروه‌های آموزشی دانشکده، ارائه و نقد مقالات علمی روز دنیا در مقابل اساتید و دانشجویان",
            "organizer": "گروه آموزشی دانشکده",
            "level": "university",
            "estimated_duration_days": 1,
            "impact_score": 5,
            "difficulty": "medium",
            "resume_section": "executive_records",
            "tags": ["Journal Club", "نقد مقاله", "critical appraisal"],
            "outcomes": ["توانایی نقد مقاله", "مهارت ارائه", "ارتباط با اساتید"],
        },
        {
            "id": "e6",
            "title": "وبینار تخصصی حوزه پژوهش",
            "description": "شرکت در وبینارهای تخصصی آنلاین در حوزه‌های مختلف پژوهش پزشکی، روش‌شناسی تحقیق یا حوزه‌های بالینی تخصصی",
            "organizer": "انجمن‌های علمی / دانشگاه‌ها",
            "level": "national",
            "estimated_duration_days": 2,
            "impact_score": 4,
            "difficulty": "easy",
            "resume_section": "training_courses",
            "tags": ["وبینار", "آنلاین", "آموزش مداوم"],
            "outcomes": ["گواهی شرکت", "به‌روز ماندن در حوزه", "امتیاز آموزش مداوم"],
        },
        {
            "id": "e7",
            "title": "کنگره تخصصی رشته (مرتبط با تخصص هدف)",
            "description": "شرکت در کنگره‌های تخصصی مرتبط با رشته تخصصی هدف، آشنایی با فضای تخصص، ارتباط با رزیدنت‌ها و فلوها",
            "organizer": "انجمن تخصصی",
            "level": "national",
            "estimated_duration_days": 3,
            "impact_score": 8,
            "difficulty": "easy",
            "resume_section": "presentations",
            "tags": ["کنگره تخصصی", "networking", "رشته هدف"],
            "outcomes": ["آشنایی با رشته هدف", "ارتباط با متخصصان", "اطلاعات درباره رزیدنسی"],
        },
        {
            "id": "e8",
            "title": "رویداد networking بین‌المللی IFMSA",
            "description": "شرکت در رویدادها و تبادل‌های علمی سازمان بین‌المللی دانشجویان پزشکی (IFMSA)، ارتباط با دانشجویان پزشکی سراسر جهان",
            "organizer": "IFMSA / انجمن علمی دانشجویی",
            "level": "international",
            "estimated_duration_days": 2,
            "impact_score": 7,
            "difficulty": "medium",
            "resume_section": "executive_records",
            "tags": ["IFMSA", "بین‌المللی", "networking"],
            "outcomes": ["ارتباط بین‌المللی", "تجربه در سازمان بین‌المللی", "مهارت زبانی"],
        },
        {
            "id": "e9",
            "title": "المپیاد علمی دانشجویان پزشکی",
            "description": "شرکت در المپیادهای علمی دانشجویی (آمار، پژوهش، علوم پایه)، رقابت علمی سطح ملی و کسب رتبه برای ارتقاء پرونده",
            "organizer": "وزارت بهداشت / دانشگاه‌ها",
            "level": "national",
            "estimated_duration_days": 3,
            "impact_score": 9,
            "difficulty": "hard",
            "resume_section": "executive_records",
            "tags": ["المپیاد", "رقابت علمی", "رتبه ملی"],
            "outcomes": ["مدال / تقدیرنامه ملی", "امتیاز ویژه استعداد درخشان", "اعتبار علمی"],
        },
    ],

    "project": [
        {
            "id": "p1",
            "title": "پروژه تحقیقاتی مستقل دانشجویی",
            "description": "طراحی و اجرای یک مطالعه تحقیقاتی مستقل با راهنمایی استاد مشاور، از تعریف سوال تحقیق تا جمع‌آوری داده و تحلیل نتایج",
            "organizer": "دانشگاه / معاونت تحقیقات",
            "level": "university",
            "estimated_duration_days": 60,
            "impact_score": 9,
            "difficulty": "hard",
            "resume_section": "projects",
            "tags": ["تحقیق مستقل", "پروژه دانشجویی", "PI"],
            "outcomes": ["تجربه PI بودن", "داده برای مقاله", "یادگیری مدیریت پروژه تحقیقاتی"],
        },
        {
            "id": "p2",
            "title": "همکاری به عنوان RA در طرح تحقیقاتی استاد",
            "description": "شرکت فعال در یک طرح تحقیقاتی مصوب به عنوان Research Assistant: جمع‌آوری داده، ورود داده، کمک در تحلیل و نگارش",
            "organizer": "استاد راهنما / گروه تحقیقاتی",
            "level": "university",
            "estimated_duration_days": 90,
            "impact_score": 8,
            "difficulty": "medium",
            "resume_section": "projects",
            "tags": ["RA", "همکاری تحقیقاتی", "تیم تحقیق"],
            "outcomes": ["تجربه تیم تحقیقاتی", "co-authorship احتمالی", "مهارت جمع‌آوری داده"],
        },
        {
            "id": "p3",
            "title": "Elective تحقیقاتی در مرکز پژوهشی",
            "description": "گذراندن دوره elective در یک مرکز تحقیقاتی معتبر داخلی یا خارجی، کار در آزمایشگاه یا تیم تحقیقاتی متخصص",
            "organizer": "مرکز تحقیقاتی / بیمارستان دانشگاهی",
            "level": "national",
            "estimated_duration_days": 45,
            "impact_score": 9,
            "difficulty": "medium",
            "resume_section": "projects",
            "tags": ["Elective", "مرکز تحقیقاتی", "تجربه عملی"],
            "outcomes": ["گواهی elective", "تجربه در محیط تحقیقاتی واقعی", "ارتباط با محققان"],
        },
        {
            "id": "p4",
            "title": "توسعه اپلیکیشن یا ابزار دیجیتال سلامت",
            "description": "طراحی و توسعه یک اپلیکیشن پزشکی، ابزار سلامت دیجیتال یا نرم‌افزار کمکی بالینی؛ مناسب برای علاقه‌مندان به health-tech",
            "organizer": "تیم دانشجویی / استارتاپ",
            "level": "university",
            "estimated_duration_days": 75,
            "impact_score": 8,
            "difficulty": "hard",
            "resume_section": "projects",
            "tags": ["health-tech", "اپلیکیشن پزشکی", "نوآوری"],
            "outcomes": ["محصول دیجیتال قابل نمایش", "تجربه کارآفرینی", "portfolio غیرسنتی"],
        },
        {
            "id": "p5",
            "title": "پروژه آموزشی و تولید محتوای علمی",
            "description": "تولید محتوای آموزشی پزشکی (ویدیو، پادکست، مقاله عمومی)، راه‌اندازی کانال آموزشی یا طراحی برنامه آموزشی برای همتایان",
            "organizer": "فردی / انجمن علمی",
            "level": "university",
            "estimated_duration_days": 30,
            "impact_score": 6,
            "difficulty": "medium",
            "resume_section": "projects",
            "tags": ["تولید محتوا", "آموزش", "peer teaching"],
            "outcomes": ["پورتفولیوی محتوایی", "مهارت ارتباطی", "تدریس به همتایان"],
        },
        {
            "id": "p6",
            "title": "پروژه خدمات اجتماعی سلامت (Community Health)",
            "description": "طراحی و اجرای برنامه آموزش بهداشت عمومی، غربالگری، یا مداخله سلامت محور در جامعه؛ مناسب برای تقویت بعد اجتماعی پرونده",
            "organizer": "مرکز بهداشت / NGO / دانشگاه",
            "level": "national",
            "estimated_duration_days": 20,
            "impact_score": 6,
            "difficulty": "medium",
            "resume_section": "executive_records",
            "tags": ["بهداشت جامعه", "Community Health", "خدمات اجتماعی"],
            "outcomes": ["تجربه کار اجتماعی", "گواهی خدمات", "تقویت Statement of Purpose"],
        },
        {
            "id": "p7",
            "title": "عضویت و فعالیت در انجمن علمی دانشجویی",
            "description": "عضویت فعال در انجمن علمی دانشکده به عنوان مسئول، دبیر یا عضو هیئت مدیره؛ برگزاری رویداد، مدیریت تیم و ارتقاء مهارت‌های رهبری",
            "organizer": "انجمن علمی دانشجویی",
            "level": "university",
            "estimated_duration_days": 180,
            "impact_score": 7,
            "difficulty": "medium",
            "resume_section": "executive_records",
            "tags": ["انجمن علمی", "رهبری", "مدیریت"],
            "outcomes": ["تجربه مدیریتی", "مهارت‌های رهبری", "امتیاز سابقه اجرایی"],
        },
        {
            "id": "p8",
            "title": "پروژه داده‌کاوی و AI در پزشکی",
            "description": "انجام یک پروژه تحلیل داده با رویکرد Machine Learning یا AI در حوزه پزشکی؛ از dataset تا مدل‌سازی و نتیجه‌گیری",
            "organizer": "تیم تحقیقاتی / آنلاین",
            "level": "university",
            "estimated_duration_days": 60,
            "impact_score": 9,
            "difficulty": "hard",
            "resume_section": "projects",
            "tags": ["AI", "Machine Learning", "داده‌کاوی", "پزشکی دیجیتال"],
            "outcomes": ["پروژه AI پزشکی", "آشنایی با Python/ML", "publication احتمالی"],
        },
    ],

    "research": [
        {
            "id": "r1",
            "title": "نگارش و ارسال Case Report",
            "description": "گزارش یک مورد بالینی جالب یا نادر؛ مناسب‌ترین نقطه شروع برای ورود به دنیای نشر علمی. شامل: انتخاب case، مرور ادبیات، نگارش و ارسال",
            "organizer": "مستقل / با استاد راهنما",
            "level": "university",
            "estimated_duration_days": 45,
            "impact_score": 7,
            "difficulty": "medium",
            "resume_section": "articles",
            "tags": ["Case Report", "مقاله اول", "نشر"],
            "outcomes": ["اولین مقاله منتشرشده", "تجربه peer review", "ارتقاء رزومه پژوهشی"],
        },
        {
            "id": "r2",
            "title": "نگارش و ارسال Original Article",
            "description": "نگارش مقاله اصیل بر اساس داده‌های جمع‌آوری‌شده در یک مطالعه observational یا experimental؛ هدف‌گذاری برای ژورنال‌های ایندکس",
            "organizer": "مستقل / تیم تحقیقاتی",
            "level": "university",
            "estimated_duration_days": 90,
            "impact_score": 10,
            "difficulty": "hard",
            "resume_section": "articles",
            "tags": ["Original Article", "مقاله اصیل", "ISI", "Scopus"],
            "outcomes": ["مقاله پژوهشی اصیل", "نقش first author", "امتیاز بالا در پرونده"],
        },
        {
            "id": "r3",
            "title": "نگارش و ارسال Review Article",
            "description": "نگارش مقاله مروری جامع درباره یک موضوع پزشکی با جستجوی سیستماتیک ادبیات، خلاصه‌سازی و نتیجه‌گیری انتقادی",
            "organizer": "مستقل / با استاد",
            "level": "university",
            "estimated_duration_days": 60,
            "impact_score": 8,
            "difficulty": "hard",
            "resume_section": "articles",
            "tags": ["Review Article", "مروری", "ادبیات علمی"],
            "outcomes": ["مقاله مروری منتشرشده", "تسلط بر موضوع", "مهارت مرور ادبیات"],
        },
        {
            "id": "r4",
            "title": "نگارش Letter to Editor / Short Communication",
            "description": "نگارش نامه به سردبیر یا Short Communication در واکنش به یک مقاله منتشرشده یا برای انتشار یک یافته مختصر اما مهم",
            "organizer": "مستقل",
            "level": "university",
            "estimated_duration_days": 14,
            "impact_score": 5,
            "difficulty": "easy",
            "resume_section": "articles",
            "tags": ["Letter to Editor", "Short Communication", "نشر سریع"],
            "outcomes": ["نشر سریع", "مهارت نگارش مختصر", "شروع کارنامه نشر"],
        },
        {
            "id": "r5",
            "title": "ثبت پروپوزال در معاونت تحقیقات و دریافت کد",
            "description": "تکمیل فرآیند ثبت رسمی طرح تحقیقاتی در سامانه معاونت تحقیقات دانشگاه، دریافت کد طرح، تصویب در شورای پژوهشی",
            "organizer": "معاونت تحقیقات دانشگاه",
            "level": "university",
            "estimated_duration_days": 21,
            "impact_score": 7,
            "difficulty": "medium",
            "resume_section": "projects",
            "tags": ["پروپوزال", "کد طرح", "شورای پژوهشی"],
            "outcomes": ["کد طرح تحقیقاتی", "بودجه دانشگاهی احتمالی", "مجوز رسمی تحقیق"],
        },
        {
            "id": "r6",
            "title": "انجام و انتشار Systematic Review",
            "description": "اجرای کامل یک مرور سیستماتیک با PRISMA: تعریف PICO، ثبت در PROSPERO، جستجو در ۵+ پایگاه داده، ارزیابی کیفیت و متاآنالیز",
            "organizer": "تیم تحقیقاتی",
            "level": "national",
            "estimated_duration_days": 120,
            "impact_score": 10,
            "difficulty": "hard",
            "resume_section": "articles",
            "tags": ["Systematic Review", "PRISMA", "PROSPERO", "متاآنالیز"],
            "outcomes": ["مقاله SR با impact factor بالا", "تسلط بر روش‌شناسی SR", "registration در PROSPERO"],
        },
        {
            "id": "r7",
            "title": "ثبت کارآزمایی بالینی در IRCT",
            "description": "آماده‌سازی و ثبت یک کارآزمایی بالینی در پایگاه کارآزمایی‌های بالینی ایران (IRCT) و دریافت IRCT ID",
            "organizer": "معاونت تحقیقات / کمیته اخلاق",
            "level": "national",
            "estimated_duration_days": 30,
            "impact_score": 9,
            "difficulty": "hard",
            "resume_section": "projects",
            "tags": ["IRCT", "کارآزمایی بالینی", "RCT"],
            "outcomes": ["IRCT ID", "ثبت رسمی کارآزمایی", "اعتبار مطالعه"],
        },
        {
            "id": "r8",
            "title": "نگارش فصل کتاب یا textbook",
            "description": "مشارکت در نگارش یک فصل از کتاب آموزشی یا مرجع پزشکی به دعوت ناشر یا ویراستار، زیر نظر استاد با تجربه",
            "organizer": "ناشر / استاد ویراستار",
            "level": "national",
            "estimated_duration_days": 60,
            "impact_score": 8,
            "difficulty": "hard",
            "resume_section": "articles",
            "tags": ["فصل کتاب", "chapter", "کتاب مرجع"],
            "outcomes": ["فصل کتاب در رزومه", "تجربه نگارش جامع", "همکاری با ناشر"],
        },
        {
            "id": "r9",
            "title": "ارائه Abstract در کنفرانس (Oral/Poster)",
            "description": "ارسال Abstract به یک کنفرانس علمی، دریافت پذیرش و ارائه نتایج تحقیق به صورت Oral Presentation یا Poster در جمع متخصصان",
            "organizer": "کنفرانس مربوطه",
            "level": "national",
            "estimated_duration_days": 10,
            "impact_score": 7,
            "difficulty": "medium",
            "resume_section": "presentations",
            "tags": ["Abstract", "Oral Presentation", "Poster", "کنفرانس"],
            "outcomes": ["گواهی ارائه", "تجربه نقد علمی", "publication در proceedings"],
        },
        {
            "id": "r10",
            "title": "پایان‌نامه / تزِ دکترا (رشته پزشکی)",
            "description": "اجرای پروژه پایان‌نامه دکترای عمومی یا تخصصی به عنوان یک پروژه تحقیقاتی جامع با هدف نشر مقاله از آن",
            "organizer": "دانشگاه / استاد راهنما",
            "level": "university",
            "estimated_duration_days": 180,
            "impact_score": 10,
            "difficulty": "hard",
            "resume_section": "articles",
            "tags": ["پایان‌نامه", "تز", "دکترا"],
            "outcomes": ["مقاله از پایان‌نامه", "تجربه تحقیق جامع", "دفاع رسمی"],
        },
    ],
}


def get_all_items_flat():
    """برگرداندن همه آیتم‌ها به صورت یک لیست صاف"""
    items = []
    for category, category_items in STATIC_ITEMS.items():
        for item in category_items:
            items.append({**item, "category": category})
    return items


def get_item_by_id(item_id: str):
    """پیدا کردن آیتم با شناسه"""
    for category, category_items in STATIC_ITEMS.items():
        for item in category_items:
            if item["id"] == item_id:
                return {**item, "category": category}
    return None


CATEGORY_LABELS = {
    "course": "دوره آموزشی",
    "event": "رویداد / کنگره",
    "project": "پروژه",
    "research": "تحقیق / مقاله",
}

LEVEL_LABELS = {
    "university": "دانشگاهی",
    "national": "ملی",
    "international": "بین‌المللی",
}

DIFFICULTY_LABELS = {
    "easy": "آسان",
    "medium": "متوسط",
    "hard": "دشوار",
}