# Generated by Django 6.0.6 on 2026-06-26 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان پروژه')),
                ('slug', models.SlugField(allow_unicode=True, max_length=350, unique=True, verbose_name='اسلاگ')),
                ('short_description', models.CharField(max_length=500, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('category', models.CharField(choices=[('clinical', 'بالینی'), ('basic_science', 'علوم پایه'), ('systematic_review', 'مرور سیستماتیک / متاآنالیز'), ('case_report', 'گزارش مورد'), ('epidemiology', 'اپیدمیولوژی'), ('public_health', 'سلامت عمومی'), ('medical_education', 'آموزش پزشکی'), ('ai_health', 'هوش مصنوعی در سلامت'), ('other', 'سایر')], max_length=40, verbose_name='دسته\u200cبندی')),
                ('status', models.CharField(choices=[('idea', 'ایده اولیه'), ('proposal', 'در مرحله پروپوزال'), ('ethics', 'در انتظار کد اخلاق'), ('collecting_data', 'جمع\u200cآوری داده'), ('analysis', 'تحلیل داده'), ('writing', 'نگارش مقاله'), ('submitted', 'سابمیت شده'), ('published', 'منتشر شده'), ('paused', 'متوقف / غیرفعال')], max_length=40, verbose_name='وضعیت پروژه')),
                ('collaboration_status', models.CharField(choices=[('open', 'جذب همکار فعال'), ('limited', 'جذب محدود'), ('closed', 'عدم جذب همکار')], default='open', max_length=20, verbose_name='وضعیت جذب همکار')),
                ('visibility', models.CharField(choices=[('public', 'عمومی'), ('private', 'خصوصی')], default='public', max_length=20, verbose_name='نمایش')),
                ('field', models.CharField(blank=True, max_length=200, verbose_name='حوزه تخصصی')),
                ('keywords', models.CharField(blank=True, max_length=300, verbose_name='کلیدواژه\u200cها')),
                ('methodology', models.TextField(blank=True, verbose_name='روش انجام / متدولوژی')),
                ('required_skills', models.TextField(blank=True, verbose_name='مهارت\u200cهای موردنیاز همکار')),
                ('expected_output', models.CharField(blank=True, help_text='مثلاً مقاله، پوستر، ارائه، پروپوزال، گرانت', max_length=250, verbose_name='خروجی مورد انتظار')),
                ('supervisor', models.CharField(blank=True, max_length=200, verbose_name='استاد راهنما / مسئول علمی')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='دانشگاه / مرکز تحقیقاتی')),
                ('ethics_code', models.CharField(blank=True, max_length=100, verbose_name='کد اخلاق')),
                ('start_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ شروع')),
                ('estimated_end_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ پایان تقریبی')),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ظرفیت جذب همکار')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('owner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_projects', to='accounts.profile', verbose_name='پروفایل ثبت\u200cکننده')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_research_projects', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'پروژه / تحقیق',
                'verbose_name_plural': 'پروژه\u200cها و تحقیقات',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بروزرسانی')),
                ('text', models.TextField(verbose_name='متن بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='project.researchproject', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'بروزرسانی پروژه',
                'verbose_name_plural': 'بروزرسانی\u200cهای پروژه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('principal_investigator', 'مجری اصلی'), ('supervisor', 'استاد راهنما'), ('co_researcher', 'همکار پژوهشی'), ('data_collector', 'جمع\u200cآوری داده'), ('statistician', 'تحلیل\u200cگر آماری'), ('writer', 'نویسنده'), ('translator', 'مترجم'), ('other', 'سایر')], max_length=40, verbose_name='نقش')),
                ('contribution', models.TextField(blank=True, verbose_name='شرح همکاری')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='accounts.profile', verbose_name='پروفایل')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='project.researchproject', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'عضو پروژه',
                'verbose_name_plural': 'اعضای پروژه',
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان فایل')),
                ('file', models.FileField(upload_to='project_files/%Y/%m/', verbose_name='فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project.researchproject', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'فایل پروژه',
                'verbose_name_plural': 'فایل\u200cهای پروژه',
            },
        ),
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام درخواست همکاری')),
                ('skills', models.TextField(blank=True, verbose_name='مهارت\u200cها و تجربه مرتبط')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت درخواست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('applicant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_applications', to='accounts.profile', verbose_name='پروفایل متقاضی')),
                ('applicant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_applications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر متقاضی')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='project.researchproject', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'درخواست همکاری',
                'verbose_name_plural': 'درخواست\u200cهای همکاری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['status', 'category'], name='project_res_status_d8a280_idx'),
        ),
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['visibility', 'is_active'], name='project_res_visibil_5bc64f_idx'),
        ),
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['created_at'], name='project_res_created_2ceae7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'profile')},
        ),
        migrations.AlterUniqueTogether(
            name='projectapplication',
            unique_together={('project', 'applicant_profile')},
        ),
    ]
