# Generated by Django 6.0.6 on 2026-06-26 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='رزومه من', max_length=200, verbose_name='عنوان رزومه')),
                ('purpose', models.CharField(choices=[('residency', 'رزیدنتی / استعداد درخشان'), ('faculty', 'هیات علمی'), ('fellowship', 'فلوشیپ / ریسرچ پوزیشن خارج'), ('job', 'بازار کار بالینی'), ('general', 'عمومی')], default='general', max_length=50, verbose_name='هدف رزومه')),
                ('template', models.CharField(choices=[('classic', 'کلاسیک حرفه\u200cای'), ('modern', 'مدرن دو ستونه'), ('academic', 'آکادمیک پژوهشی'), ('minimal', 'مینیمال')], default='classic', max_length=30, verbose_name='قالب رزومه')),
                ('use_ai', models.BooleanField(default=False, verbose_name='استفاده از AI')),
                ('ai_enhanced', models.BooleanField(default=False, verbose_name='بهبود یافته با AI')),
                ('include_education', models.BooleanField(default=True, verbose_name='تحصیلات')),
                ('include_articles', models.BooleanField(default=True, verbose_name='مقالات')),
                ('include_presentations', models.BooleanField(default=True, verbose_name='ارائه\u200cها')),
                ('include_executive', models.BooleanField(default=True, verbose_name='سوابق اجرایی')),
                ('include_training', models.BooleanField(default=True, verbose_name='دوره\u200cهای آموزشی')),
                ('include_clinical', models.BooleanField(default=True, verbose_name='سوابق بالینی')),
                ('include_languages', models.BooleanField(default=True, verbose_name='زبان\u200cها')),
                ('include_skills', models.BooleanField(default=True, verbose_name='مهارت\u200cها')),
                ('include_extracurricular', models.BooleanField(default=True, verbose_name='فعالیت\u200cهای فوق برنامه')),
                ('ai_summary', models.TextField(blank=True, verbose_name='خلاصه حرفه\u200cای (AI)')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='resumes/pdf/', verbose_name='فایل PDF')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='resumes/docx/', verbose_name='فایل Word')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رزومه',
                'verbose_name_plural': 'رزومه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
