# course/data.py

VIDEO_DATABASE = {
    'olampiad_elmi': [
        {
            'id': 'ola_001',
            'title': 'المپیاد کارآفرینی دوره 18',
            'category': 'olampiad_elmi',
            'shortDesc': 'دوره آموزش و منتورینگ المپیاد کارآفرینی',
            'longDesc': 'دوره هجدهم المپیاد کارآفرینی، فرصتی است برای تجربه‌ی واقعی کار تیمی، حل مسئله و نوآوری در فضای علوم پزشکی.\n در این مسیر، شرکت‌کنندگان هم‌زمان با آموزش مفاهیم کلیدی نوآوری، بیزنس‌مدل و طراحی راه‌حل، از منتورینگ شخصی متناسب با پروژه خود بهره‌مند می‌شوند.',
            'stars': 5,
            'duration': '30 ساعت',
            'mainPrice': '1,875,000',
            'discountPrice': '1,680,000',
            'percentage': '10',
            'instructor': 'جمعی از مدال آوران',
            'thumbnail': '/static/image_card/IMG_20260506_215201.jpg',
            'videoLink': 'https://example.com',
            'active': True,
        },
        {
            'id': 'ola_002',
            'title': 'المپیاد هنر و رسانه دوره 18',
            'category': 'olampiad_elmi',
            'shortDesc': 'دوره آموزش و منتورینگ المپیاد هنر و رسانه',
            'longDesc': 'دوره آموزش و منتورینگ المپیاد هنر و رسانه در المپیاد علمی دانشجویی علوم پزشکی، فرصتی برای آشنایی با نقش هنر و رسانه در آموزش سلامت.',
            'stars': 5,
            'duration': '25 ساعت',
            'mainPrice': '1,850,000',
            'discountPrice': '1,660,000',
            'percentage': '10',
            'instructor': 'جمعی از مدال آوران',
            'thumbnail': '/static/image_card/IMG_20260506_215206.jpg',
            'videoLink': 'https://example.com',
            'active': True,
        },
        {
            'id': 'ola_003',
            'title': 'المپیاد مدیریت در نظام سلامت دوره 18',
            'category': 'olampiad_elmi',
            'shortDesc': 'دوره آموزش و منتورینگ المپیاد مدیریت در نظام سلامت',
            'longDesc': 'دوره آموزش و منتورینگ المپیاد مدیریت در نظام سلامت فرصتی است برای آشنایی عمیق‌تر با پشت‌صحنه اداره نظام سلامت.',
            'stars': 5,
            'duration': '25 ساعت',
            'mainPrice': '1,780,000',
            'discountPrice': '1,600,000',
            'percentage': '10',
            'instructor': 'جمعی از مدال آوران',
            'thumbnail': '/static/image_card/IMG_20260506_215211.jpg',
            'videoLink': 'https://example.com',
            'active': True,
        },
        {
            'id': 'ola_004',
            'title': 'المپیاد نانو دانشجویی دوره 15',
            'category': 'olampiad_elmi',
            'shortDesc': 'دوره آموزش و منتورینگ المپیاد نانو دانشجویی',
            'longDesc': 'دوره آموزش و منتورینگ المپیاد نانو دانشجویی (دوره ۱۵) فرصتی برای یادگیری عمیق مفاهیم فناوری نانو و آماده‌سازی هدفمند برای حضور در این رقابت علمی است.',
            'stars': 5,
            'duration': '30 ساعت',
            'mainPrice': '2,100,000',
            'discountPrice': '1,890,000',
            'percentage': '10',
            'instructor': 'جمعی از مدال آوران',
            'thumbnail': '/static/image_card/549fd6a7-9a20-4a94-be1e-52a6659cc8da.png.jpeg',
            'videoLink': 'https://example.com',
            'active': True,
        },
        {
            'id': 'ola_005',
            'title': 'المپیاد پرستاری دوره 5',
            'category': 'olampiad_elmi',
            'shortDesc': 'دوره آموزش و منتورینگ المپیاد پرستاری',
            'longDesc': 'دوره آموزش و منتورینگ المپیاد پرستاری (دوره ۵) فرصتی برای آشنایی عمیق‌تر با مباحث علمی و مهارتی حوزه پرستاری.',
            'stars': 5,
            'duration': '25 ساعت',
            'mainPrice': '1,950,000',
            'discountPrice': '1,650,000',
            'percentage': '15',
            'instructor': 'جمعی از مدال آوران',
            'thumbnail': '/static/image_card/IMG_20260506_215220.jpg',
            'videoLink': 'https://example.com',
            'active': True,
        },
    ],
    'tahghighat': [
        {
            'id': 'tah_001',
            'title': 'پروپوزال نویسی مقدماتی',
            'category': 'tahghighat',
            'shortDesc': 'نحوه نگارش استاندارد پروپوزال پژوهشی',
            'longDesc': 'دوره پروپوزال‌نویسی مقدماتی، نقشه راه علمی شما برای تبدیل یک «ایده پژوهشی» به یک «طرح استاندارد و قابل‌اجرا» است.',
            'stars': 5,
            'duration': '15 ساعت',
            'mainPrice': '1,250,000',
            'discountPrice': '1,060,000',
            'percentage': '15',
            'instructor': 'دپارتمان پژوهشی',
            'thumbnail': '/static/image_card/IMG_20232506_215701.jpeg',
            'videoLink': 'https://example.com',
            'active': True,
        },
    ],
    'maghaleh': [
        {
            'id': 'mag_001',
            'title': 'مقاله نویسی مقدماتی',
            'category': 'maghaleh',
            'shortDesc': 'نحوه نگارش و سابمیت مقاله در مجلات داخلی',
            'longDesc': 'دوره مقاله‌نویسی مقدماتی برای دانشجویانی طراحی شده است که می‌خواهند با اصول نگارش و ارسال مقالات علمی در مجلات داخلی آشنا شوند.',
            'stars': 5,
            'duration': '20 ساعت',
            'mainPrice': '2,450,000',
            'discountPrice': '2,080,000',
            'percentage': '15',
            'instructor': 'دپارتمان پژوهشی',
            'thumbnail': '/static/image_card/IMG_20260506_215224.jpg',
            'videoLink': 'https://example.com',
            'active': True,
        },
        {
            'id': 'mag_002',
            'title': 'مقاله نویسی پیشرفته',
            'category': 'maghaleh',
            'shortDesc': 'نحوه نگارش و سابمیت مقاله در مجلات ISI',
            'longDesc': 'دوره مقاله‌نویسی پیشرفته برای پژوهشگرانی طراحی شده است که قصد دارند سطح نگارش علمی خود را به استانداردهای بین‌المللی ارتقا دهند.',
            'stars': 5,
            'duration': '25 ساعت',
            'mainPrice': '4,990,000',
            'discountPrice': '4,490,000',
            'percentage': '10',
            'instructor': 'دپارتمان پژوهشی',
            'thumbnail': '/static/image_card/71f2f4b2-bee2-4a3e-9bc4-aa7dca42dd4b.png.jpeg',
            'videoLink': 'https://example.com',
            'active': True,
        },
    ],
    'maghale_congress': [
        {
            'id': 'con_001',
            'title': 'طراحی پوستر کنگره',
            'category': 'maghale_congress',
            'shortDesc': 'نحوه طراحی پوستر جهت ارائه خلاصه مقالات',
            'longDesc': 'دوره آموزشی طراحی پوستر در کنگره با هدف توانمندسازی پژوهشگران و دانشجویان برای ارائه بصری و حرفه‌ای دستاوردهای علمی طراحی شده است.',
            'stars': 4,
            'duration': '5 ساعت',
            'mainPrice': '999,000',
            'discountPrice': '799,000',
            'percentage': '20',
            'instructor': 'دپارتمان پژوهشی',
            'thumbnail': '/static/image_card/1778095626950.jpg',
            'videoLink': 'https://example.com',
            'active': True,
        },
        {
            'id': 'con_002',
            'title': 'دوره اورژانسی کنگره ملی پژوهش و فناوری',
            'category': 'maghale_congress',
            'shortDesc': 'تدوین خلاصه مقاله جهت حضور در کنگره سالیانه در کمتر از یک هفته',
            'longDesc': 'دوره اورژانسی کنگره ملی پژوهش و فناوری برای دانشجویان و پژوهشگرانی طراحی شده که قصد دارند در زمان محدود، خلاصه مقاله خود را آماده کنند.',
            'stars': 4,
            'duration': '7 ساعت',
            'mainPrice': '1,100,000',
            'discountPrice': '935,000',
            'percentage': '15',
            'instructor': 'دپارتمان پژوهشی',
            'thumbnail': '/static/image_card/1778096846187.jpg',
            'videoLink': 'https://example.com',
            'active': True,
        },
        {
            'id': 'con_003',
            'title': 'ارائه علمی در کنگره',
            'category': 'maghale_congress',
            'shortDesc': 'آمادگی جهت ارائه خلاصه مقالات در کنگره ملی پژوهش و فناوری',
            'longDesc': 'دوره ارائه علمی در کنگره برای پژوهشگرانی طراحی شده که می‌خواهند خلاصه‌مقاله خود را به شکلی حرفه‌ای ارائه کنند.',
            'stars': 4,
            'duration': '2 ساعت',
            'mainPrice': '',
            'discountPrice': '',
            'percentage': '',
            'instructor': 'دپارتمان پژوهشی',
            'thumbnail': '/static/image_card/1778095626950.jpg',
            'videoLink': 'https://example.com',
            'active': True,
        },
    ],
    'ketab': [
        {
            'id': 'ket_001',
            'title': 'مقدمات تالیف کتاب',
            'category': 'ketab',
            'shortDesc': 'آشنایی با اصول اولیه تالیف کتاب در حوزه تخصصی',
            'longDesc': 'دوره مقدمات تألیف کتاب برای افرادی طراحی شده که دانش، تجربه یا تخصص ارزشمندی در یک حوزه مشخص دارند اما نمی‌دانند چگونه آن را به شکل یک کتاب منسجم ارائه کنند.',
            'stars': 4,
            'duration': '2 ساعت',
            'mainPrice': '',
            'discountPrice': '',
            'percentage': '',
            'instructor': 'محمدرضا علیمردانی',
            'thumbnail': '/static/image_card/b85d4f94-4fed-402a-a849-f3bae0c1bafc.jpeg',
            'videoLink': 'https://example.com',
            'active': True,
        },
    ],
    'ekhtera': [
        {
            'id': 'ekh_001',
            'title': 'ثبت اختراع داخلی',
            'category': 'ekhtera',
            'shortDesc': 'نحوه نوشتن اظهارنامه و گرفتن گواهی ثبت اختراع داخلی',
            'longDesc': 'دوره ثبت اختراع داخلی به شما کمک می‌کند تا ایده یا نوآوری خود را به‌صورت رسمی در قالب یک پتنت قابل ثبت تبدیل کنید.',
            'stars': 5,
            'duration': '20 ساعت',
            'mainPrice': '4,500,000',
            'discountPrice': '3,600,000',
            'percentage': '20',
            'instructor': 'دپارتمان ثبت اختراع',
            'thumbnail': '/static/image_card/071349cf-65dd-4aea-889a-65c551d4a62f.jpeg',
            'videoLink': 'https://example.com',
            'active': True,
        },
        {
            'id': 'ekh_002',
            'title': 'ثبت اختراع بین المللی',
            'category': 'ekhtera',
            'shortDesc': 'نحوه ثبت اختراع به صورت بین المللی (US patent)',
            'longDesc': 'دوره ثبت اختراع بین‌المللی به شما کمک می‌کند تا نوآوری خود را فراتر از مرزهای کشور ثبت و محافظت کنید.',
            'stars': 5,
            'duration': '30 ساعت',
            'mainPrice': '13,500,000',
            'discountPrice': '12,150,000',
            'percentage': '10',
            'instructor': 'دپارتمان ثبت اختراع',
            'thumbnail': '/static/image_card/IMG_20260506_232826.jpeg',
            'videoLink': 'https://example.com',
            'active': True,
        },
    ],
    'noavari': [
        {
            'id': 'nov_001',
            'title': 'راه اندازی استارتاپ های حوزه سلامت',
            'category': 'noavari',
            'shortDesc': 'صفر تا صد چگونگی راه اندازی استارتاپ های سلامت محور',
            'longDesc': 'دوره راه‌اندازی استارتاپ‌های حوزه سلامت یک مسیر جامع و مرحله‌به‌مرحله برای افرادی است که می‌خواهند ایده‌های سلامت‌محور خود را به یک کسب‌وکار واقعی تبدیل کنند.',
            'stars': 5,
            'duration': '20 ساعت',
            'mainPrice': '5,750,000',
            'discountPrice': '4,900,000',
            'percentage': '15',
            'instructor': 'دپارتمان نوآوری و کارآفرینی',
            'thumbnail': '/static/image_card/1778094301755.jpg',
            'videoLink': 'https://example.com',
            'active': True,
        },
        {
            'id': 'nov_002',
            'title': 'ثبت شرکت در مرکز رشد',
            'category': 'noavari',
            'shortDesc': 'نحوه ثبت شرکت و استقرار در مرکز رشد دانشگاه',
            'longDesc': 'دوره آموزشی ثبت شرکت در مرکز رشد، راهنمای جامع و گام‌به‌گامی است برای دانشجویان، فناوران و نخبگانی که می‌خواهند ایده‌های نوآورانه خود را عملی کنند.',
            'stars': 4,
            'duration': '3 ساعت',
            'mainPrice': '500,000',
            'discountPrice': '350,000',
            'percentage': '30',
            'instructor': 'حسن اسماعیلی',
            'thumbnail': '/static/image_card/d763e9f4-17fb-4f4c-9c3e-d77bf08ba4ff.jpeg',
            'videoLink': 'https://example.com',
            'active': True,
        },
        {
            'id': 'nov_003',
            'title': 'ساخت محصولات سلامت دیجیتال بدون کدنویسی',
            'category': 'noavari',
            'shortDesc': 'طراحی و ساخت محصولات سلامت دیجیتال با متدولوژی Low code & No code',
            'longDesc': 'دوره ساخت محصولات سلامت دیجیتال بدون کدنویسی برای افرادی طراحی شده که می‌خواهند ایده‌های سلامت‌محور خود را بدون برنامه‌نویسی عملی کنند.',
            'stars': 5,
            'duration': '12 ساعت',
            'mainPrice': '1,999,000',
            'discountPrice': '1,800,000',
            'percentage': '10',
            'instructor': 'پوریا فتح الله زاده',
            'thumbnail': '/static/image_card/22f6ecb4-44d4-44ba-95c7-f09f711f1c46.jpeg',
            'videoLink': 'https://example.com',
            'active': True,
        },
    ],
    'jashnvare': [
        {
            'id': 'jash_001',
            'title': 'آمادگی برای استارتاپ ویکندهای کشوری',
            'category': 'jashnvare',
            'shortDesc': 'چگونگی ایده پردازی و مقام آوری در استارتاپ ویکند',
            'longDesc': 'دوره آمادگی برای استارتاپ ویکندهای کشوری برای افرادی طراحی شده که می‌خواهند با آمادگی واقعی و ذهنیت برنده وارد رویدادهای رقابتی شوند.',
            'stars': 4,
            'duration': '3 ساعت',
            'mainPrice': '600,000',
            'discountPrice': '510,000',
            'percentage': '15',
            'instructor': 'محمد محسن خدابنده',
            'thumbnail': '/static/image_card/1778096277918.jpg',
            'videoLink': 'https://example.com',
            'active': True,
        },
        {
            'id': 'jash_002',
            'title': 'ایده پردازی فناورانه',
            'category': 'jashnvare',
            'shortDesc': 'روش های ایده پردازی فناورانه در حوزه سلامت',
            'longDesc': 'دوره ایده‌پردازی فناورانه در حوزه سلامت برای افرادی طراحی شده که می‌خواهند از دل چالش‌های واقعی نظام سلامت به ایده‌های نوآورانه برسند.',
            'stars': 4,
            'duration': '2 ساعت',
            'mainPrice': '',
            'discountPrice': '',
            'percentage': '',
            'instructor': 'ایمان رجائی',
            'thumbnail': '/static/image_card/1ea0ff8a-359f-41e0-87cb-bb6bd6156658.jpeg',
            'videoLink': 'https://example.com',
            'active': True,
        },
    ],
    'bedone_dastebandi': [
        {
            'id': 'bedone_001',
            'title': 'آشنایی با بند ک استعداد درخشان',
            'category': 'bedone_dastebandi',
            'shortDesc': 'آشنایی با ماده های مختلف بند ک استعدادهای درخشان',
            'longDesc': 'دوره آشنایی با بند «ک» استعدادهای درخشان برای دانشجویانی طراحی شده که قصد دارند از مزایای آیین‌نامه‌های ویژه استعدادهای درخشان بهره‌مند شوند.',
            'stars': 4,
            'duration': '2 ساعت',
            'mainPrice': '',
            'discountPrice': '',
            'percentage': '',
            'instructor': 'ستاره شهسواری',
            'thumbnail': '/static/image_card/images-3.jpeg',
            'videoLink': 'https://example.com',
            'active': True,
        },
    ],
}